name: Build Mod

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build mod
      run: ./gradlew build

    - name: Upload built mod
      uses: actions/upload-artifact@v4
      with:
        name: AmetystowyMechMod
        path: build/libs/*.jar                         
     - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Fix gradle wrapper permissions
      run: chmod +x gradle/wrapper/gradle-wrapper.jar

    - name: Build mod
      run: ./gradlew build
